server:
  port: 8084
  
spring:
  config:
    import: optional:configserver:http://localhost:8085
  application:
    name: API-GATEWAY
    
  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
          - Path=/users/**
          
        - id: RATING-SERVICE
          uri: lb://RATING-SERVICE
          predicates:
          - Path=/ratings/**
          
        - id: HOTEL-SERVICE
          uri: lb://HOTEL-SERVICE
          predicates:
          - Path=/hotels/**, /staffs/**
          
          
 # Okta configuration for API gateway         
          
okta:
  oauth2:
    issuer: https://dev-79418932.okta.com/oauth2/default
    audience: api://default
    client-id: 0oace2ckseP162Oiu5d7
    client-secret: gtoFl6svJjHGjyfAHCx3v_ROtGko3cWuECjrCBgo2IL6cwJCF9J4bKa4wzd32k2t
    scopes: openid, profile, email, offline_access
    
    
    
    
    
    
        