server:
  port: 8083
  
spring:
  config:
    import: optional:configserver:http://localhost:8085
  application:
    name: RATING-SERVICE
  data:
    mongodb:
      uri: mongodb://localhost:27017/
      database: Microservices
      
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      
      
# Okta configuration for API gateway         
          
okta:
  oauth2:
    issuer: https://dev-79418932.okta.com/oauth2/default
    audience: api://default